[workspace]
members = [
    "tools/xtask",
    "tools/image_builder",
    "tools/initrd_gen",
    "src/bin/init",
    "src/bin/devmgr",
    "src/bin/netmgr",
    "src/bin/nettest",
    "src/bin/testing",
    "src/kernel",
    "src/lib/twizzler-queue-raw",
    "src/lib/twizzler-queue",
    "src/lib/twizzler-net",
    "src/lib/twizzler-async",
    "src/lib/twizzler-nando",
    "src/lib/twizzler-object"
]
resolver = "2"

[workspace.metadata]
initrd = [
    "crate:init",
    "crate:devmgr",
    "crate:netmgr",
    "crate:nettest",
    "crate:testing",
]

[profile.release]
debug = true

[patch.'https://github.com/dbittman/twizzler-abi']
twizzler-abi = { path = "src/lib/twizzler-abi" }

[patch.'https://github.com/twizzler-operating-system/twizzler-abi']
twizzler-abi = { path = "src/lib/twizzler-abi" }

[patch.crates-io]
twizzler-abi = { path = "src/lib/twizzler-abi" }
num_cpus = { git = "https://github.com/twizzler-operating-system/num_cpus" }
parking_lot = { git = "https://github.com/twizzler-operating-system/parking_lot" }