[package]
name = "twz-rt"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
twizzler-runtime-api = { path = "../../lib/twizzler-runtime-api", features = [
    "runtime",
] }
thiserror = "1.0"
tracing = "0.1"
twizzler-abi = { path = "../../lib/twizzler-abi", default-features = false }
dynlink = { path = "../dynlink" }
bitflags = "2.4"
talc = { version = "3.1", default-features = false }

[features]
runtime = []
default = ["runtime"]
