[package]
name = "logboi-impl"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
secgate = { path = "../../../runtime/secgate" }
twizzler-runtime = { path = "../../../runtime/rt" }

[features]
api = []
