[package]
name = "logboi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
secgate = { path = "../../runtime/secgate" }
twizzler-runtime = { path = "../../runtime/rt" }
logboi-impl = { path = "logboi-impl", features = ["api"] }
