[package]
name = "naming-test"
version = "0.1.0"
edition = "2021"

[dependencies]
twizzler-abi = { path = "../../lib/twizzler-abi" }
naming-core = { path = "../../lib/naming/naming-core" }
twizzler-minruntime = {path = "../../rt/minimal"} # TODO: Implement Kani dependecy feature 

