[package]
name = "logboi-impl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ['dylib']

[dependencies]
secgate = { path = "../../secgate" }
ctor = {version = "*", default-features = false }
