[package]
name = "monitor-api"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twizzler-rt-abi = { path = "../../abi/rt-abi" }
twizzler-abi = { path = "../../lib/twizzler-abi", default-features = false }
secgate = { path = "../secgate" }
dynlink = { path = "../dynlink" }
bitflags = "2"
