[alias]
xtask = "run --release --target-dir=.target-xtask --package xtask --"
build-all = "run --release --target-dir=.target-xtask --package xtask -- build"
check-all = "run --release --target-dir=.target-xtask --package xtask -- check"
make-image = "run --release --target-dir=.target-xtask --package xtask -- make-image"
start-qemu = "run --release --target-dir=.target-xtask --package xtask -- start-qemu"
bootstrap = "run --release --target-dir=.target-xtask --package xtask -- bootstrap"

[build]
rustdocflags = "-Zunstable-options --enable-index-page"