[package]
name = "lethe"
version = "0.1.0"
edition = "2021"

[dependencies]
crypter = { git = "https://github.com/lemosyne/crypter.git" }
embedded-io = "0.4.0"
hasher = { git = "https://github.com/lemosyne/hasher.git" }
hex = "0.4.3"
khf = { git = "https://github.com/lemosyne/khf.git" }
kms = { git = "https://github.com/lemosyne/kms.git" }
rand = { version = "0.8.5", default-features = false }
thiserror = "1.0.40"
