name: Docs

on:
  push:
    branches: [ main ]
    paths-ignore: '**/README.md'

env:
  CARGO_TERM_COLOR: always
  LLVM_CONFIG_PATH: /usr/bin/llvm-config-18

jobs: 
  setup:
    uses: ./.github/workflows/setup.yml
  build:
    needs: setup
    runs-on: self-hosted

    steps:
    - name: Keygen
      run: |
        echo "$DEPLOY_KEY_DATA" > deploy_key
      shell: bash
      env:
        DEPLOY_KEY_DATA : ${{secrets.DOCS_KEY}}
    - name: Chmod
      run: chmod 0600 deploy_key
    - name: Clone
      run: GIT_SSH_COMMAND='ssh -i deploy_key' git clone git@github.com:twizzler-operating-system/twizzler-operating-system.github.io.git
    - name: Install mdbook
      run: |
        mkdir mdbook
        curl -Lf https://github.com/rust-lang/mdBook/releases/download/v0.4.13/mdbook-v0.4.13-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo `pwd`/mdbook >> $GITHUB_PATH
    - name: Bootstrap Toolchain
      run: cargo bootstrap
    - name: Build
      run: cargo doc-all
    - name: Copy
      run: mkdir -p twizzler-operating-system.github.io/nightly && cp -r target/x86_64-unknown-twizzler/doc twizzler-operating-system.github.io/nightly/
    - name: Build Book
      run: cd doc && mdbook build
    - name: Copy Book
      run: cp -r doc/book twizzler-operating-system.github.io/nightly/
    - name: Config-1
      run: git config --global user.name "Deploy Actions"
    - name: Config-2
      run: git config --global user.email "null@null.com"
    - name: Stamp
      run: |
        echo "generated at '" $(date) "' from commit ID " $(git rev-parse HEAD) > twizzler-operating-system.github.io/stamp
        cd twizzler-operating-system.github.io && git add stamp
    - name: Commit
      run: cd twizzler-operating-system.github.io && git add -A && git commit -am "Update"
    - name: Push
      run: cd twizzler-operating-system.github.io && GIT_SSH_COMMAND='ssh -i ../deploy_key' git push
