name: Kani Build and Run

on:
  push:
    branches: [ "alex_kani_2", "main" ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted

    steps:
    # Step 1: Cleanup
    - name: Cleanup Workspace
      run: |
        ls -la
        rm -rf ./* || true
        rm -rf ./.??* || true
        ls -la
    
    # Step 2: Checkout the Repository
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    # Step 3: Install the Stable Toolchain
    - name: Install Rust Stable Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    
    # Step 4: Install Kani dependencies (optional, depending on kani setup)
    - name: Install Kani Dependencies
      run: |
        rustup component add rust-src
        rustup component add llvm-tools-preview
    
    # Step 5: Build Kani
    - name: Build Kani
      run: |
        cd kani
        cargo build-dev

    # Step 6: Run Kani with the appropriate flags
    - name: Run Kani with Cargo
      run: |
        ./kani/scripts/cargo-kani --workspace --exclude monitor -Z stubbing -Z unstable-options --output-into-files

