name: kani_workflow

on:
  push:
    branches: [ main, kani_refactor ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Cleanup
        run: |
          ls -la 
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la 
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.82.0
          override: true
      - name: Bootstrap Toolchain
        run: cargo bootstrap

      # Use the Kani GitHub Action, passing in the -p nvme argument
      - name: Run Kani
        uses: model-checking/kani-github-action@v1.1
        with:
          args: '--enable-unstable -Zunstable-options --ignore-global-asm --output-into-files -Zstubbing -p twizzler-abi'

